# WARNING: Do not change the name of this folder, keep `setup-envs`.
# other workflows need the name of the action to work.

# https://docs.github.com/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

name: "Setup deps envs"
description: |
  Setup and cache deps envs for hatch and pre-commit.
  will:
      `pip install -r requirements.txt -U`
      create and cache hatch venv
      create and cache pre-commit venv
  NOTE: use `setup-python` first

inputs:
  python-version:
    description: "steps.setup-python.outputs.python-version"
    required: true
  python-path:
    description: "steps.setup-python.outputs.python-path"
    required: true
  cache:
    description: "Whether to use cache; set `true` to use cache"
    default: "false"
    required: false

outputs:
  hatch-cache-hit:
    description: "hatch venv cache hit"
    value: ${{ steps.cache-hatch-venv.outputs.cache-hit }}
  pre-commit-cache-hit:
    description: "pre-commit venv cache hit"
    value: ${{ steps.cache-pre-commit-venv.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # pip install hatch and pre-commit
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -U
        python -m pip freeze --local

    # cache hatch venv
    - name: cache hatch venv
      id: cache-hatch-venv
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v3
      env:
        CACHE_VERSION: v1
      with:
        path: |
          ./.venv-docs
          ./.venv-fmt
          ./.venv-default
        key: "\
          hatch-venv-${{ runner.os }}-${{ env.CACHE_VERSION }}-\
          python${{ inputs.python-version }}-\
          ${{ inputs.python-path }}-\
          ${{ hashFiles('pyproject.toml', 'requirements.txt') }}\
          "
        restore-keys: hatch-venv-${{ runner.os }}-${{ env.CACHE_VERSION }}-

    # cache pre-commit venv
    # modified from: https://github.com/pre-commit/action/blob/c7d159c2092cbfaab7352e2d8211ab536aa2267c/action.yml
    #      https://pre-commit.com/#github-actions-example
    - name: cache pre-commit venv
      uses: actions/cache@v3
      id: cache-pre-commit-venv
      if: ${{ inputs.cache == 'true' }}
      env:
        CACHE_VERSION: v1
      with:
        path: ~/.cache/pre-commit
        key: "\
          pre-commit-3-${{ runner.os }}-${{ env.CACHE_VERSION }}-\
          python${{ inputs.python-version }}-\
          ${{ inputs.python-path }}-\
          ${{ hashFiles('.pre-commit-config.yaml') }}\
          "
        restore-keys: pre-commit-3-${{ runner.os }}-${{ env.CACHE_VERSION }}-

    # Create hatch venv
    # required before first running of pre-commit local system hooks,
    #     read `#Environment setup` in `CONTRIBUTING.md` for more info
    - name: create hatch venv
      shell: bash
      run: |
        for i in {1..100}; do echo -n "="; done; echo
        hatch env create default
        hatch run default:pip freeze --local

        for i in {1..100}; do echo -n "="; done; echo
        hatch env create fmt
        hatch run fmt:pip freeze --local

        for i in {1..100}; do echo -n "="; done; echo
        hatch env create docs
        hatch run docs:pip freeze --local

    # init pyright-python to avoid `npm ERR! code ENOTEMPTY`
    #     Issue: https://github.com/RobertCraigie/pyright-python/issues/200
    - name: init pyright-python
      shell: bash
      # Ignore warnings to improve performance
      #     https://github.com/RobertCraigie/pyright-python?tab=readme-ov-file#ignore-warnings
      # Set env var in github workflow
      #     ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env
      run: |
        echo "PYRIGHT_PYTHON_IGNORE_WARNINGS=1" >> "$GITHUB_ENV"
        hatch run default:pyright --help

    # NOTE: Do not run `hatch shell <env>` to enter another shell,
    #     which wiil crash github workflow on ubuntu
